name: flutter_google_maps_webservices
description: Google maps web services for flutter (Geocoding, Places, Directions, Distance Matrix, Photos, Timezone, Static Map)
version: 1.1.2
repository: https://github.com/dev-juju/flutter_google_maps_webservices
homepage: https://github.com/dev-juju/flutter_google_maps_webservices

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.2
  meta: ^1.16.0
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.25.12
  build_runner: ^2.4.14
  coverage: ^1.0.0
